name: Test Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run custom Bash script action
        uses: ./  # This points to the action in your current repo
        with:
          name: "accelario"
        env:
          VIRTUALIZATION_IP: ${{ vars.10.10.12.140 }}
          TGT_HOME_ID: ${{ vars.DBHOME-ORA-135 }}
          SNAPSHOT_ID: ${{ vars.Snapshot_00100377 }}
          VIRTUALIZATION_LOGIN: ${{ secrets.admin }}
          VIRTUALIZATION_PASSWORD: ${{ secrets.password }}
